language: python

python:
  - "2.7"
  - "3.4"

env:
  - PYTHON=$(which python)

before_install:
  - wget http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz
  - tar -xvf nlopt-2.4.2.tar.gz
  - cd nlopt-2.4.2

install:
  - ./configure --prefix=$(dirname $(dirname $(which python))) --enable-shared
  - make
  - make install

script:
  - python -c 'import numpy'
  - python -c 'import nlopt'
