language: python

python:
  - "2.7"
  - "3.4"

before_install:
  - wget http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz
  - tar -xvf nlopt-2.4.2.tar.gz
  - cd nlopt-2.4.2

install:
  - ./configure PYTHON=`which python` --prefix= --enable-shared

script:
  - python -c 'import numpy'
  - which python
  - echo "$WORKON_HOME"